spring:
  application:
    name: notificationapp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:9090/realms/proselyte
server:
  port: 8092
